# Site settings
author: Emma
title: Emma's Blog
header-img: img/home-bg.png
email: emmamariafitzgerald@gmail.com
copyright_name: Emma
description: > # this means to ignore newlines until "baseurl:"
  Blogging through my Flatiron Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  EmmaMFitzGerald

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
